# The gates CI runs, in order. `step "<name>" <command...>` stops at the first failure. Keep identical to CI.
step "diff is clean of whitespace errors" git diff --check
GO="docker run --rm -v $PWD:/src -w /src -v go-mod-cache:/go/pkg/mod golang:1.25"
step "go build" $GO go build ./...
step "go vet" $GO go vet ./...
step "go test" $GO go test ./...
